### ISSUE TITLE
Lettrines

### ISSUE THREAD

**Issue by YohannDeguin** [e-ditiones/ODD17#6]
Bonjour @alexbartz. Serait-il possible, pour le lvl 1, d'ajouter la possibilité d'un élément `<hi>` ? Il y a des lettrines qu'il peut être intéressant de signaler, à mon avis. 
Merci beaucoup,

Yohann

**Comment by alexbartz** [comment]
Bonjour @YohannDeguin,
Je vous remercie pour votre remarque.
Nous sommes en train de travailler à une mise à jour des ODDs et nous pensions justement ajouter l'élément `<hi @rend=""> pour signaler les lettrines ou toute autre distinction graphique. Cet élément sera disponible dès le niveau 1, puisqu'il permet d'ajouter des informations qui concernant la forme du document. 
Je vous enverrai un nouveau message dès que les ODDs seront mis à jour.
Je reste à votre disposition pour tout autre commentaire.

Alexandre

**Comment by alexbartz** [comment]
@YohannDeguin,  l'ODD de niveau 1 a été mis à jour, vous pouvez donc le télécharger et l'associer à votre document. Il devrait être maintenant possible d'utiliser `hi` mais s'il y a le moindre souci, n'hésitez pas à me le signaler.
https://github.com/e-ditiones/ODD17/tree/master/out (le fichier : ODD-1.rng)

**Comment by YohannDeguin** [comment]
Test probant ! Merci beaucoup. :)
